### ISSUE TITLE
robust method does not work

### ISSUE THREAD

**Issue by jingzbu** [hbhzwj/GAD#12]
./cmdgad detect -m robust -c /home/jzh/Dropbox/Research/Anomaly_Detection/Experimental_Results/lognormal/gen-self-check-file.py --pic_show --alpha -0.5
WARNING:util:Cannot find [socketIO_client], real-time ability is disabled.
WARNING:util:Cannot import sql related function, reading for sql server is not supported
Probably you forget to specify some options? run ./cmdgad <exper> -h for more information.
Traceback (most recent call last):
  File "./cmdgad", line 56, in main
    get_exper(args.experiment, res_args).run()
  File "/home/jzh/Research/Anomaly_Detection/gad/gad/Experiment/Detect.py", line 93, in run
    detector = self.detect()
  File "/home/jzh/Research/Anomaly_Detection/gad/gad/Experiment/Detect.py", line 89, in detect
    self.res_args)
  File "/home/jzh/Research/Anomaly_Detection/gad/gad/Detector/API.py", line 95, in detect
    detector.detect(data_handler, rdh)
  File "/home/jzh/Research/Anomaly_Detection/gad/gad/Detector/RobustDetector.py", line 314, in detect
    lamb_mf, lamb_mb = zip(*StoDetector.FBAnoDetector.save_threshold(self, data_file))
  File "/home/jzh/Research/Anomaly_Detection/gad/gad/Detector/StoDetector.py", line 597, in save_threshold
    original_option = self.desc['detect_window_info']
KeyError: 'detect_window_info'

**Comment by jingzbu** [comment]
Fixed by replacing [save_threshold] (https://github.com/hbhzwj/GAD/blob/master/gad/Detector/StoDetector.py#L612) function.
